package Lexico;

import java_cup.runtime.Symbol;

parser code
{:
	private Symbol s;
	
	public void syntax_error (Symbol s){
		this.s = s;
	}
	
	public Symbol getS(){
		return this.s;
	}
	:};
	
	ABRIR_TABELA, MOSTRAR, DE, ONDE, ORDENAR_POR, DECRESCENTE, CRESCENTE, EM_CONJUNTO_COM, ATRAVES_DA_LIGACAO, UNIDA_COM, AGRUPAR_POR, FILTRO_DO_GRUPO, CONTAR, MEDIA, VALOR_MINIMO, VALOR_MAXIMO, SOMATORIA, OU, EH, VAZIO, .E., CONTENDO;              

	
	
	
	