
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiladorprojeto;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LINHA = 15;
  public static final int OPLOG = 26;
  public static final int ASPAS = 14;
  public static final int SENAO = 9;
  public static final int IGUAL = 13;
  public static final int INT = 7;
  public static final int PUBLICO = 2;
  public static final int ABREPAR = 16;
  public static final int ERROR = 33;
  public static final int FECHACHA = 19;
  public static final int ID = 31;
  public static final int OPATRI = 28;
  public static final int PARA = 10;
  public static final int NUM = 32;
  public static final int SUB = 22;
  public static final int STRING = 6;
  public static final int DADO = 25;
  public static final int PONTOV = 20;
  public static final int MULT = 23;
  public static final int EOF = 0;
  public static final int PRINCIPAL = 5;
  public static final int DIV = 24;
  public static final int OPBOOL = 30;
  public static final int VAZIO = 4;
  public static final int error = 1;
  public static final int FECHAPAR = 17;
  public static final int ABRECHA = 18;
  public static final int SE = 8;
  public static final int FACA = 11;
  public static final int OPREL = 27;
  public static final int SOMA = 21;
  public static final int ESTATICO = 3;
  public static final int ENQUANTO = 12;
  public static final int OPINCR = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUBLICO",
  "ESTATICO",
  "VAZIO",
  "PRINCIPAL",
  "STRING",
  "INT",
  "SE",
  "SENAO",
  "PARA",
  "FACA",
  "ENQUANTO",
  "IGUAL",
  "ASPAS",
  "LINHA",
  "ABREPAR",
  "FECHAPAR",
  "ABRECHA",
  "FECHACHA",
  "PONTOV",
  "SOMA",
  "SUB",
  "MULT",
  "DIV",
  "DADO",
  "OPLOG",
  "OPREL",
  "OPATRI",
  "OPINCR",
  "OPBOOL",
  "ID",
  "NUM",
  "ERROR"
  };
}

